# Development
name = "crimson-boat-ae6e"
main = "src/worker.js"
compatibility_date = "2024-10-26"

[vars]
UUID = 'd08dcc76-3bb0-4008-bdbe-bbc74e3e89de'
proxy = '47.74.155.26'

# wrangler.toml (wrangler v3.79.0^)
[observability]
enabled = true
head_sampling_rate = 1
